"""Create database

Revision ID: a0914bc9e808
Revises: 
Create Date: 2023-12-01 20:29:33.277637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app

# revision identifiers, used by Alembic.
revision: str = 'a0914bc9e808'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('patronymic', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_task', sa.Integer(), nullable=True),
    sa.Column('performer', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('created', 'taken_to_work', 'done', name='status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performer'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task'), 'tasks', ['parent_task'], unique=False)
    op.create_index(op.f('ix_tasks_performer'), 'tasks', ['performer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_performer'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
