"""Update database

Revision ID: fae3d766a1b7
Revises: 164e06254db4
Create Date: 2023-12-03 18:15:24.667563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae3d766a1b7'
down_revision: Union[str, None] = '164e06254db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'status_enum', ['created', 'taken_to_work', 'done'],
                        [('tasks', 'status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'status_enum', [],
                        [('tasks', 'status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
